function drawField(ctx,w,h,seed){const r=rngFrom(`${effectiveSeed()}|${seed}|${state.palette}|${state.family}`),p=PALETTES[state.palette%PALETTES.length];ctx.fillStyle=p[0];ctx.fillRect(0,0,w,h);const glow=ctx.createRadialGradient(w*.45,h*.4,0,w*.5,h*.5,Math.max(w,h)*.8);glow.addColorStop(0,rgba(p[1],.07));glow.addColorStop(1,'rgba(0,0,0,.1)');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);ctx.globalCompositeOperation='screen';const energy=state.mode==='music'?state.audioLevel:state.mode==='live'?.55:0;
if(state.family===0){for(let k=0;k<12+state.density/4;k++){ctx.strokeStyle=rgba(p[1+k%4],.16+r()*.5);ctx.lineWidth=1+r()*4;ctx.beginPath();const cx=r()*w,cy=r()*h,base=(.04+r()*.24)*Math.min(w,h);for(let i=0;i<=90;i++){const a=i/90*Math.PI*2,rr=base+k*3+Math.sin(a*(3+(k%5))+state.phase)*10*(1+energy);const x=cx+Math.cos(a)*rr,y=cy+Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.stroke()}}
else if(state.family===1){for(let b=0;b<20+state.density/2;b++){let x=r()*w,y=r()*h*.2,a=Math.PI/2+(r()-.5);ctx.strokeStyle=rgba(p[1+b%4],.2+r()*.55);ctx.lineWidth=.8+r()*4;ctx.beginPath();ctx.moveTo(x,y);for(let i=0;i<24;i++){a+=(r()-.5)*.6+Math.sin(state.phase+i+b)*.02*energy;x+=Math.cos(a)*(5+r()*13);y+=Math.sin(a)*(5+r()*13);ctx.lineTo(x,y)}ctx.stroke()}}
else if(state.family===2){ctx.save();ctx.translate(w/2,h/2);for(let i=28;i>1;i--){const s=i/28*Math.max(w,h)*.72;ctx.strokeStyle=rgba(p[1+i%4],.15+.6*(1-i/28));ctx.lineWidth=1+i%5;ctx.beginPath();const sides=4+i%4;for(let j=0;j<=sides;j++){const a=j/sides*Math.PI*2+state.phase*.02,rr=s*(.52+.15*Math.sin(i*.4+j));const x=Math.cos(a)*rr,y=Math.sin(a)*rr;j?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.stroke()}ctx.restore()}
else if(state.family===3){for(let i=0;i<20+state.density/2;i++){const x=r()*w,y=r()*h,rad=8+r()*35;ctx.strokeStyle=rgba(p[1+i%4],.25+r()*.5);ctx.fillStyle=rgba(p[2+i%3],.05+r()*.15);ctx.lineWidth=1+r()*3;ctx.beginPath();ctx.arc(x,y,rad*(1+energy*.1*Math.sin(state.phase+i)),0,Math.PI*2);ctx.fill();ctx.stroke()}}
else if(state.family===4){ctx.save();ctx.translate(w/2,h*.55);ctx.strokeStyle=rgba(p[1],.75);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-h*.35);ctx.quadraticCurveTo(Math.sin(state.phase)*12*energy,0,0,h*.35);ctx.stroke();for(let side of[-1,1])for(let i=0;i<12+state.density/8;i++){const y=-h*.3+i*h*.6/(12+state.density/8);ctx.strokeStyle=rgba(p[2+i%3],.25+.35*r());ctx.lineWidth=.7+r()*2;ctx.beginPath();ctx.moveTo(0,y);ctx.quadraticCurveTo(side*w*.12,y-30,side*w*(.18+r()*.18),y+(r()-.5)*60);ctx.stroke()}ctx.restore()}
else if(state.family===5){for(let s=0;s<3+state.density/20;s++){const cx=r()*w,cy=r()*h;ctx.strokeStyle=rgba(p[1+s%4],.3+r()*.5);ctx.lineWidth=1+r()*4;ctx.beginPath();for(let i=0;i<180;i++){const a=i/180*Math.PI*2*(4+r()*7)+state.phase*.08,rr=i/180*Math.min(w,h)*(.14+r()*.28);const x=cx+Math.cos(a)*rr,y=cy+Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()}}
else if(state.family===6){ctx.save();ctx.translate(w/2,h/2);for(let i=0;i<18+state.density/4;i++){const rx=w*(.08+r()*.42),ry=h*(.06+r()*.34),a=r()*Math.PI;ctx.save();ctx.rotate(a);ctx.strokeStyle=rgba(p[1+i%4],.18+r()*.5);ctx.lineWidth=.7+r()*2.3;ctx.beginPath();ctx.ellipse(0,0,rx,ry,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle=rgba(p[2+i%3],.7);ctx.beginPath();const q=state.phase*.03+i;ctx.arc(Math.cos(q)*rx,Math.sin(q)*ry,2+r()*4+energy*2,0,Math.PI*2);ctx.fill();ctx.restore()}ctx.restore()}
else{const size=Math.max(26,80-state.density*.5);for(let y=-size;y<h+size;y+=size)for(let x=-size;x<w+size;x+=size){ctx.strokeStyle=rgba(p[1+((x+y)/size|0)%4+4>>0],.18+r()*.45);ctx.lineWidth=.7+r()*2;ctx.beginPath();const sides=3+Math.floor(r()*4),rad=size*(.3+r()*.3);for(let j=0;j<=sides;j++){const a=j/sides*Math.PI*2+state.phase*.01,px=x+Math.cos(a)*rad,py=y+Math.sin(a)*rad;j?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.stroke()}}
ctx.globalCompositeOperation='source-over';}
function render(){const[pw,ph]=canvasSize(),[cols,rows]=layoutDims();if(playerType==='panel'){const c=canvases[0],idx=Math.min(state.layout,panelNumber)-1;c.width=pw;c.height=ph;const x=c.getContext('2d');if(state.composition==='continuous'){const m=document.createElement('canvas');m.width=pw*cols;m.height=ph*rows;drawField(m.getContext('2d'),m.width,m.height,'MASTER');x.drawImage(m,(idx%cols)*pw,Math.floor(idx/cols)*ph,pw,ph,0,0,pw,ph)}else drawField(x,pw,ph,`PANEL-${idx+1}`);return}
if(state.composition==='continuous'){const m=document.createElement('canvas');m.width=pw*cols;m.height=ph*rows;drawField(m.getContext('2d'),m.width,m.height,'MASTER');canvases.forEach((c,i)=>{c.width=pw;c.height=ph;c.getContext('2d').drawImage(m,(i%cols)*pw,Math.floor(i/cols)*ph,pw,ph,0,0,pw,ph)})}else canvases.forEach((c,i)=>{c.width=pw;c.height=ph;drawField(c.getContext('2d'),pw,ph,`PANEL-${i+1}`)})}
function animate(ts){requestAnimationFrame(animate);if(state.paused||state.mode==='paper'||state.mode==='still')return;if(ts-state.lastFrame<70)return;state.lastFrame=ts;if(analyser&&audioData){analyser.getByteFrequencyData(audioData);let s=0;for(let i=0;i<audioData.length*.45;i++)s+=audioData[i];state.audioLevel=clamp(s/(audioData.length*.45*155),0,1.4)}else if(state.mode==='music')state.audioLevel=.35+.65*Math.pow(Math.max(0,Math.sin(ts*.005)),7);state.phase+=.006*state.speed*(state.mode==='music'?(1+state.audioLevel):.7);render()}
