function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('on');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('on'),1400)}
function syncUI(){const[c,r]=layoutDims();$('#layoutLabel').textContent=`${c} × ${r}`;$('#compositionLabel').textContent=state.composition==='continuous'?'One artwork':'Seed family';$('#displayModeLabel').textContent=state.mode[0].toUpperCase()+state.mode.slice(1);$('#familyLabel').textContent=FAMILY[state.family];$('#densityLabel').textContent=state.density;$('#speedLabel').textContent=state.speed;$('#aspectLabel').textContent=state.aspect==='wide'?'Wide 16:9':state.aspect==='classic'?'Classic 4:3':'Square 1:1';$('#cycleLabel').textContent=state.cycle==='manual'?'Manual':`Every ${state.cycle}`;$('#cycleSelect').value=state.cycle;$('#seedInput').value=state.seed;$('#statusMode').textContent=state.mode.toUpperCase();$('#statusSeed').textContent=state.seed;$('#statusFamily').textContent=FAMILY[state.family].toUpperCase();$('#statusScreens').textContent=state.layout;$('#statusDot').classList.toggle('live',!state.paused&&(state.mode==='live'||state.mode==='music'));$('#modeBadge').textContent=`${state.layout} ${state.layout===1?'screen':'screens'} · ${state.composition==='continuous'?'one artwork':'one seed family'}`;$$('[data-layout]').forEach(b=>b.classList.toggle('on',+b.dataset.layout===state.layout));$$('[data-composition]').forEach(b=>b.classList.toggle('on',b.dataset.composition===state.composition));$$('[data-mode]').forEach(b=>b.classList.toggle('on',b.dataset.mode===state.mode));$$('[data-aspect]').forEach(b=>b.classList.toggle('on',b.dataset.aspect===state.aspect))}
function randomSeed(){state.seed=['EMVY','GRID','WALL','LIVE','ART'][Math.floor(Math.random()*5)]+'-'+String(Math.floor(Math.random()*10000)).padStart(4,'0');persist();syncUI();render();toast('New deterministic seed')}
function newPalette(){state.palette=(state.palette+1)%PALETTES.length;persist();render();toast('Palette changed')}
function setMode(m){state.mode=m;persist();syncUI();render()}
function setLayout(n){state.layout=+n;persist();rebuildGrid()}
function setComposition(c){state.composition=c;persist();syncUI();render()}
function refreshInstallLinks(){const links=[];for(let i=1;i<=state.layout;i++)links.push(`SCREEN ${i}\n${playerURL('panel',i)}`);$('#playerUrls').value=links.join('\n\n');$('#installSummary').textContent=`${state.layout} screen${state.layout===1?'':'s'} · ${state.aspect==='wide'?'16:9':state.aspect==='classic'?'4:3':'1:1'} · ${state.cycle}`}
function openInstall(){refreshInstallLinks();$('#installModal').classList.add('on')}
$('#newArtBtn').onclick=randomSeed;$('#paletteBtn').onclick=newPalette;$('#pauseBtn').onclick=()=>{state.paused=!state.paused;$('#pauseBtn').textContent=state.paused?'▶':'Ⅱ';syncUI()};
$$('[data-layout]').forEach(b=>b.onclick=()=>setLayout(b.dataset.layout));$$('[data-composition]').forEach(b=>b.onclick=()=>setComposition(b.dataset.composition));$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('[data-aspect]').forEach(b=>b.onclick=()=>{state.aspect=b.dataset.aspect;persist();applyDisplayGeometry();syncUI();render()});
$('#prevFamily').onclick=()=>{state.family=(state.family+FAMILY.length-1)%FAMILY.length;persist();syncUI();render()};$('#nextFamily').onclick=()=>{state.family=(state.family+1)%FAMILY.length;persist();syncUI();render()};
$('#seedApply').onclick=()=>{const v=$('#seedInput').value.trim();if(v){state.seed=v.toUpperCase();persist();syncUI();render();toast('Seed loaded')}};$('#seedInput').onkeydown=e=>{if(e.key==='Enter')$('#seedApply').click()};
$('#densityRange').oninput=e=>{state.density=+e.target.value;persist();syncUI();render()};$('#speedRange').oninput=e=>{state.speed=+e.target.value;persist();syncUI()};
$('#cycleSelect').onchange=e=>{state.cycle=e.target.value;cycleStamp=cycleToken();persist();syncUI();render();toast(state.cycle==='manual'?'Manual artwork':'Scheduled '+state.cycle)};
$('#installBtn').onclick=openInstall;$('#installSidebarBtn').onclick=openInstall;$('#installClose').onclick=()=>$('#installModal').classList.remove('on');$('#installModal').onclick=e=>{if(e.target===$('#installModal'))$('#installModal').classList.remove('on')};$('#openWallPlayer').onclick=()=>window.open(playerURL('wall'),'_blank','noopener');$('#copyPlayerLinks').onclick=async()=>{refreshInstallLinks();try{await navigator.clipboard.writeText($('#playerUrls').value);toast('Player links copied')}catch(e){$('#playerUrls').select();document.execCommand('copy');toast('Player links copied')}};
$('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen?.():document.documentElement.requestFullscreen?.();
$('#loadTrackBtn').onclick=()=>$('#audioFile').click();$('#audioFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const audio=$('#audio');audio.src=URL.createObjectURL(f);audio.loop=true;audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const src=audio._source||audioCtx.createMediaElementSource(audio);audio._source=src;analyser=audioCtx.createAnalyser();analyser.fftSize=256;audioData=new Uint8Array(analyser.frequencyBinCount);src.connect(analyser);analyser.connect(audioCtx.destination);await audioCtx.resume();await audio.play();$('#audioLabel').textContent=f.name.slice(0,22);setMode('music');toast('Music reactive mode')};
$('#mobileNew').onclick=randomSeed;$('#mobilePalette').onclick=newPalette;$('#mobileMode').onclick=()=>setMode(['paper','live','music','still'][(['paper','live','music','still'].indexOf(state.mode)+1)%4]);$('#mobileLayout').onclick=()=>setLayout(state.layout===1?4:state.layout===4?9:1);
window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{applyDisplayGeometry();render()},120)});
cycleStamp=cycleToken();setInterval(()=>{const n=cycleToken();if(n!==cycleStamp){cycleStamp=n;state.phase=0;render()}},1000);rebuildGrid();requestAnimationFrame(animate);
})();
