/* EMVY CHECK Living Art V2 — Canvas Grid artwork contract + loader.

   Living Art supports two visual source types:
     GENERATIVE LIVE  - the engine in engine.js, driven live by the controls
     CANVAS GRID       - curated artwork PUBLISHED from the private Canvas
                          Grid Studio, consumed here only as data

   The private Canvas Grid generator itself is never shipped to this public
   repo. What crosses the boundary is a small, stable JSON contract:

     {
       id:               string, unique
       title:            string
       seed:             string, the deterministic seed used to produce it
       palette:          string, palette name/id
       source:           string, where it came from (e.g. "canvas-grid-studio")
       layout:           "1x1" | "2x2" | "3x3"
       compositionMode:  "continuous" | "family" | "independent"
       panels:           [{ index, label }], one entry per active tile -
                          real published panels will carry an `image` URL
                          here once Canvas Grid Studio exports are published
       masterImage:       string|null, full-sheet reference image URL
       animationProfile:  { motion, speedHint } - how LIVE should evolve it
       musicProfile:      { reactive, primaryBand } - how MUSIC should react
       author:            string
     }

   No curated Canvas Grid exports exist in this public repo yet, so V2
   ships a handful of SAMPLE definitions (living-art/samples/*.json) that
   are honestly generated by the public Living Art engine itself - not
   the private generator - purely to prove out this loader/UI end to end.
   When real Canvas Grid Studio exports are published later, they drop
   into the same samples list (or a future API) with `masterImage`/
   `panels[].image` pointing at real exported PNGs, and nothing else in
   this file needs to change. */
(function (global) {
  'use strict';

  const SAMPLE_INDEX_URL = 'samples/index.json';
  const REQUIRED_FIELDS = ['id', 'title', 'seed', 'palette', 'source', 'layout', 'compositionMode'];

  function validate(def) {
    if (!def || typeof def !== 'object') return false;
    return REQUIRED_FIELDS.every(function (k) { return typeof def[k] === 'string' && def[k].length; });
  }

  function layoutToCount(layout) { return layout === '1x1' ? 1 : layout === '2x2' ? 4 : 9; }

  let catalogPromise = null;
  function listCatalog() {
    if (catalogPromise) return catalogPromise;
    catalogPromise = fetch(SAMPLE_INDEX_URL)
      .then(function (r) { if (!r.ok) throw new Error('http ' + r.status); return r.json(); })
      .then(function (list) { return Array.isArray(list) ? list : []; })
      .catch(function (err) {
        console.warn('[Living Art] Canvas Grid sample catalogue unavailable', err);
        return [];
      });
    return catalogPromise;
  }

  const defCache = {};
  function loadArtwork(id) {
    if (defCache[id]) return Promise.resolve(defCache[id]);
    return fetch('samples/' + id + '.json')
      .then(function (r) { if (!r.ok) throw new Error('http ' + r.status); return r.json(); })
      .then(function (def) {
        if (!validate(def)) throw new Error('Artwork definition failed validation: ' + id);
        defCache[id] = def;
        return def;
      });
  }

  /* Maps a Canvas Grid artwork definition onto the same {seed,family,palette}
     recipe shape the generative engine renders, using the sample-only
     `livingArtPreview` hint. Real published artwork (masterImage/panels
     populated with image URLs) would be drawn by compositing those images
     instead - that path is intentionally not built yet since there is
     nothing real to composite; the contract above is what a future loader
     needs to support it without touching the rest of the app. */
  function previewRecipe(def, engine) {
    const hint = def.livingArtPreview || {};
    const familyIndex = engine.familyIndexById(hint.family || '');
    return {
      seed: def.seed,
      family: familyIndex >= 0 ? familyIndex : engine.hashString(def.seed) % engine.FAMILIES.length,
      palette: Math.max(0, engine.PALETTES.findIndex(function (p) { return p.name === def.palette; }))
    };
  }

  global.LivingArtCanvasGrid = {
    validate: validate,
    layoutToCount: layoutToCount,
    listCatalog: listCatalog,
    loadArtwork: loadArtwork,
    previewRecipe: previewRecipe
  };
})(window);
